version: '3.8'

services:
  # Whisper-ASR service (no changes)
  whisper-asr-gpu:
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    container_name: whisper-asr-gpu

    runtime: nvidia

    # CRITICAL: Add shared memory for CUDA operations
    shm_size: '1gb'

    # Don't expose port 9000 directly - only through Caddy
    expose:
      - "9000"

    environment:
      - ASR_ENGINE=faster_whisper
      - ASR_MODEL=small
      - ASR_DEVICE=cuda
      - ASR_COMPUTE_TYPE=int8_float16  # Memory-efficient quantization
      - ASR_BEAM_SIZE=3               # Reduced from 5 (minimal quality loss)
      - ASR_BATCH_SIZE=8              # Faster processing

    volumes:
      - ./whisper-gpu-cache:/root/.cache

    restart: unless-stopped

    networks:
      - whisper-net

  # nginx reverse proxy to add CORS headers
  nginx-cors:
    image: nginx:alpine
    container_name: whisper-nginx-cors

    ports:
      - "9000:9000"  # Expose through nginx instead

    # Create nginx config inline using command
    command: >
      sh -c "echo '
      server {
          listen 9000;

          # Allow large file uploads (up to 500MB for long audio recordings)
          # Covers approximately 4+ hours of audio
          client_max_body_size 500M;

          location / {
              # CORS headers
              add_header Access-Control-Allow-Origin * always;
              add_header Access-Control-Allow-Methods \"GET, POST, OPTIONS\" always;
              add_header Access-Control-Allow-Headers \"*\" always;
              add_header Access-Control-Max-Age 3600 always;

              # Handle preflight
              if ($$request_method = OPTIONS) {
                  return 204;
              }

              # Proxy to Whisper-ASR
              proxy_pass http://whisper-asr-gpu:9000;
              proxy_set_header Host $$host;
              proxy_set_header X-Real-IP $$remote_addr;

              # Extended timeouts for very long transcription tasks
              # 1 hour of audio can take 30-45 minutes to transcribe
              proxy_connect_timeout 3600s;  # 60 minutes
              proxy_send_timeout 3600s;      # 60 minutes
              proxy_read_timeout 3600s;      # 60 minutes
          }
      }
      ' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

    restart: unless-stopped

    networks:
      - whisper-net

    depends_on:
      - whisper-asr-gpu

networks:
  whisper-net:
    driver: bridge
